language: java

jdk:
  - openjdk8

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

services:
  - docker

before_script:
  - docker-compose up -d
  - make database

script: 
  - ./gradlew clean build

after_success:
  - ./gradlew jacocoTestReport

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: wiw.nexters.com 
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read_write
    local_dir: deploy
    wait-until-deployed: true
    on:
      repo: Nexters/Strolling-of-time-API
      branch: 
        - feature/ci