language: java

jdk:
  - openjdk8

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

services:
  - docker

before_script:
  - docker-compose up -d
  - make database

script: 
  - ./gradlew clean build

after_success:
  - ./gradlew jacocoTestReport

before_deploy:
  - zip -r wiw-api build/libs/*
  - mkdir -p deploy
  - mv wiw-api.zip deploy/wiw-api.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: wiw-api-deploy
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    local_dir: deploy
    wait-until-deployed: true
    on:
      repo: Nexters/Strolling-of-time-API
      branch: feature/ci
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: wiw-api-deploy # S3 버킷
    key: wiw-api.zip # 빌드 파일을 압축해서 전달
    bundle_type: zip
    application: wiw-api # 웹 콘솔에서 등록한 CodeDeploy 어플리케이션
    deployment_group: wiw-api-group # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      repo: Nexters/Strolling-of-time-API
      branch: feature/ci
  
