version: '3'
services:
  mysql:
    image: mysql:5.7
    hostname: mysql
    container_name: api-practice
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - ${MYSQL_PORT}:3306 # MYSQL_PORT는 현재 container의 호스트의 환경변수
    env_file:
      - ./confs/mysql/dev.env # mysql container 내부에서 사용되는 환경 변수
    volumes:
      - ./confs/mysql/my.cnf:/etc/mysql/my.cnf
  mosquitto:
    image: eclipse-mosquitto:1.6.4
    hostname: mosquitto
    container_name: mosquitto
    ports:
      - 1883:1883
    volumes:
      - ./confs/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log

volumes:
  mosquitto-data:
  mosquitto-log:
