spring:
  profiles:
    active: local
---
spring:
  jwt:
    secret: aeh!IFJAIF@$#$Q ARV
    issuer: clockIsWatch
  profiles: local
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false
  datasource:
    url: >
      jdbc:mysql://localhost:${MYSQL_PORT}/${MYSQL_DATABASE}?
      autoReconnect=true&
      useSSL=false&
      useUnicode=true&
      characterEncoding=utf8&
      serverTimezone=UTC
    username: root
    password: ${MYSQL_ROOT_PASSWORD}
  jpa:
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
---
spring:
  profiles: prod
  datasource:
    url:
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false