spring:
  profiles:
    active: local
---
spring:
  jwt:
    secret: aeh!IFJAIF@$#$Q ARV
    issuer: clockIsWatch
  profiles: local
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false
  datasource:
    url: >
      jdbc:mysql://{MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?
      autoReconnect=true&
      useSSL=false&
      useUnicode=true&
      characterEncoding=utf8&
      serverTimezone=UTC
    username: ${MYSQL_USER}
    password: ${MYSQL_ROOT_PASSWORD}
  jpa:
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8080
---
spring:
  jwt:
    secret: ${JWT_SECRET}
    issuer: ${ISSUER}
  profiles: prod
  datasource:
    url: >
      jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?
      autoReconnect=true&
      useSSL=false&
      useUnicode=true&
      characterEncoding=utf8&
      serverTimezone=UTC
    username: ${MYSQL_USER}
    password: ${MYSQL_USER_PASSWORD}
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: validate